### ISSUE TITLE
Update/Get Part

### ISSUE THREAD

**Issue by jayajr** [hicsail/clotho#109]
Used Postman

Workflow:
Login
Create Device
``` json
POST @ .../api/device
{
   "name":"testingdev",
   "displayId":"testingdev",
   "parameters":[

   ],
   "partIds":[
      "59806f430aa71e158a8adef7",
      "59806f430aa71e158a8adefd",
      "59806f440aa71e158a8adf1b",
      "59806f450aa71e158a8adf33",
      "59806f460aa71e158a8adf63"
   ],
   "createSeqFromParts":"true"
}
```
Get Device
Take first subpart (the nominal part contained in the device, not the first value in partId) id
Update Part
``` json
PUT @ .../api/part/update/:id
{
    "name": "testingdev",
    "displayId": "green fluorescent protein derived from jellyfish",
    "role": "PROMOTER",
    "parameters": [
        {
            "name": "color",
            "variable": "green",
            "value": 1,
            "units": "nM"
        }
    ],
    "sequence": "ATGCGTAAA"
}
```

404 Error.

Tried GETting just the part and 404 Error as well.

**Comment by jayajr** [comment]
Error in terminal

![sep25 134452](https://user-images.githubusercontent.com/10633080/30822618-eb9d691e-a218-11e7-8a7a-4fe8c1713f27.png)

**Comment by gregfrasco** [comment]
@jayajr Thanks, will look into

**Comment by gregfrasco** [comment]
Try fix on branch 109, otherwise, try recreating the parts. I cannot reproduce since the parts are older the versioning system.

**Comment by jayajr** [comment]
I think the problem may lie in Get Part with Filter
`/api/part/:filter`


Workflow:
Login
Create Part
```JSON
POST @ .../api/part
{
   "name":"pTet"
}
```

Check Part was created
``` JSON
GET @ .../api/part/:id
```
```JSON
[
    {
        "_id": "59d0e4742167620f3978a408",
        "name": "pTet",
        "description": null,
        "userId": "5975de7aa8a63710837ba542",
        "displayId": null,
        "imageURL": null,
        "subBioDesignIds": null,
        "superBioDesignId": null,
        "type": "PART",
        "subparts": [
            {
                "_id": "59d0e4742167620f3978a40a",
                "name": "pTet",
                "description": null,
                "userId": "5975de7aa8a63710837ba542",
                "displayId": null,
                "bioDesignId": "59d0e4742167620f3978a408"
            }
        ],
        "modules": [],
        "parameters": []
    }
]
```

Searching with filter as subpart, and name as pTet
``` JSON
PUT @ .../api/part/subparts
{
    "name": "pTet"
}
```


Getting this error. Says bad username or password but the same Authentication header was used in the Create and the Get by ID

![oct01 125938](https://user-images.githubusercontent.com/10633080/31056927-b1feba5e-a6c9-11e7-8150-9d231fa4130c.png)

**Comment by gregfrasco** [comment]
The Authentication header might be a separate issue, these parts are not connected.
